#1. process execution parameters...
#2. instantiate socket and nodes list...
#3. wait for new node...
    #3.1. open new thread for processing request...
        #3.1.1 return nodes list...
        #3.1.2. wait for confirmation of connection...
            # True: add new node to nodes list using a Lock...
        #3.1.3. close connection...
